# This is a basic workflow to help you get started with Actions

name: Execute climb-warm.ipynb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 21 * * *' # 每24小时执行一次

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write  # 將 read 改為 write 以允許推送更改
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 指定你需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pandas numpy jsons # 安装需要的库

    - name: Execute Jupyter Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute climb-warm.ipynb --output executed-climb-warm.ipynb

    - name: Commit changes
      run: |
        git config --local user.name 'nekowaneko'
        git config --local user.email 'ccheng686@yahoo.com.tw'
        git add . # 添加所有更改，包括 untracked files
        git commit -m "Add changes"
        git push


    
