# This is a basic workflow to help you get started with Actions

name: Execute climb-warm.ipynb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 */24 * * *' # 每24小时执行一次

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 指定你需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pandas numpy # 安装需要的库

    - name: Execute Jupyter Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute climb-warm.ipynb --output executed-climb-warm.ipynb
