# This is a basic workflow to help you get started with Actions

name: push commit

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --local user.name 'nekowaneko'
          git config --local user.email 'ccheng686@yahoo.com.tw'
          git commit -a -m "Add changes"
          git push
