name: push commit

on:
  workflow_dispatch:

permissions:
  contents: write  # 將 read 改為 write 以允許推送更改

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --local user.name 'nekowaneko'
          git config --local user.email 'ccheng686@yahoo.com.tw'
          git add report.txt  # 添加這行來暫存新建的文件
          git commit -m "Add changes"
          git push
