# This is a basic workflow to help you get started with Actions

name: push commit

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'nekowaneko'
          git config --global user.email 'nekowaneko@users.noreply.github.com'
          git commit -am "Automated report"
          git push
